[[section-solution-strategy]]
== Solution Strategy

=== Contents

.Summary

This application is implemented using Javascript, React.js, SOLID specifications and many other dependencies gathered thanks to npm. Its architecture follows the MVC pattern.

Allows users to authenticate into the system with their SOLID account and manage their routes (stored inside their pod). These routes can be created by the user, already predefined in the system or shared by other users.

Pod decentralised data storage alongside a route shape standard provide our application with interoperability with other route management systems, like all the other Viade proyects. Moreover, GPX is also supported.

.Some solution approaches
[cols="1, 1, 3, 1"]
|===
| *Quality goal* 
| *Scenario* 
| *Solution approach* 
| *Link to Details*

| Standards
| Route data model
| Elaboration of a data model
| link:https://arquisoft.github.io/viadeSpec/[Viade data model]

| Perfect imperfection
| Application design
| The intent of fulfilling our goals while understanding that errors have their place
| link:https://simplicable.com/new/imperfection[Examples at Simplicable]

| Data ownership
| Information storage
| Personal SOLID pod storage
| link:https://solid.mit.edu/[SOLID webpage]

|===