[[section-design-decisions]]
== Design Decisions

=== _Not Use React Native_

We decided to postpone the use of React Native.

.Pros

* Allows creating apps for Android and iOS with the same code than the web application.
* Dynamic HTML pages can be easily created.

.Cons

* Will take time to learn the language.
* Less pre-created components available.
* Not much advantage in using it, as the main functions can be emulated
using a web browser for mobile phones.


=== _JSON-LD Format for Routes_

.Pros

* The use of a standard makes it easy for the application to communicate with other services.
* We follow Viade Specification, therefore making sure we can exchange information with other compatible applications.
* JSON notation which is already known by us.

.Cons

* PODs dont have yet a way to view the files in this format.

=== _Leaflet_

We chose Leaflet as our map provider.

.Pros

* It provides the advantage that is OpenSource and that it doesn't need any API Key. This
was the main reason why we discard Google Maps.
* Also with React-Leaflet library, we don't have to program the basic components such as
Map, Marker or Polyline. They came already implemented.

.Cons

* None of us has previously worked with this tool, so it's another thing to learn.

=== _Chart.js_

We chose chart_js as our plotting tool. 

.Pros

* Has react suport to ease the task of developing the charts
* It's free.
* It's well documented.

.Cons

* Needs a lot of code to configure the charts.

=== _Storing altitude for points in the POD_

.Pros

* Reduces latency when displaying points as it only checks the altitude of each point once.
* ViadeSpec points seem to follow this approach.

.Cons

* More space occupied

=== _AirMap Elevation API_

.Pros

* It's free
* Doesn't need API Key
* Easy to use (just a single GET request)

.Cons

* For some points, such as seas, lakes or oceans may not give a response.

=== _Sharing of routes_

Our approach saves all files in a private directory (that is, viade/ inside the POD). Then, when sharing, giving the user's friends rights to view the files and sending a notification to each user of the newly shared route to them.

The other approach would have been saving everything on public/ directory.

.Pros

* Privacy and sharing for particular users is allowed.
* A user can have his own private routes.

.Cons

* Harder to implement.
* If not careful may result in loss of rights on files.
* A need of learning a library or method to edit the permissions of the POD.
* Creating a notification system to inform to the receiver of the share.