[[section-design-decisions]]
== Design Decisions

=== _Use of React Native_

.Pros

* Will allow creating apps for Android and iOS with the same code than the web application.
* Dynamic HTML pages can be easily created.

.Cons

* Will take time to learn the language.


=== _KML Format for Routes_

.Pros

* The use of a standard makes it easy for the application to communicate with other services.

.Cons

* The XML notation may result in more cumbersome processing than with JSON.

=== _Leaflet_

We chose Leaflet as our map provider.

.Pros

* It provides the advantage that is OpenSource and that it doesn't need any API Key. This
was the main reason why we discard Google Maps.
* Also with React-Leaflet library, we don't have to program the basic components such as
Map, Marker or Polyline. They came already implemented.

.Cons

* None of us has previously worked with this tool, so it's another thing to learn.


=== _Other Decisions_
This part will be done in the future. Some decisions haven't been taken yet, for example:

* Features that the app will have